# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-13 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20170912_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chatmessage',
            field=models.TextField(max_length=5000),
        ),
    ]
